{"name": "test_incorrect[incorrect_data0]", "status": "passed", "attachments": [{"name": "log", "source": "e9223509-6129-4705-bbc9-ddc8889e95c6-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "incorrect_data", "value": "{'username': '1303845892@qq.com', 'password': '', 'check': '密码不能为空'}"}], "start": 1594726507808, "stop": 1594726560331, "uuid": "07798f3a-d679-40d9-bc1b-16c3a0379e43", "historyId": "e64c0af6fef26d85bcdee262d7a7479c", "testCaseId": "486418aa0944ed0ecb75b40c2b58e369", "fullName": "TestCases.test_login.TestLogin#test_incorrect", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-KFH4O7N"}, {"name": "thread", "value": "20728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}